import { lazyWithRetry } from '../utils/lazyWithRetry.js';

export const ShipperDashboard = lazyWithRetry(() => import('../pages/dashboard/ShipperDashboard.jsx'));
export const CarrierDashboard = lazyWithRetry(() => import('../pages/dashboard/CarrierDashboard.jsx'));
export const AdminDashboardPage = lazyWithRetry(() => import('../pages/admin/AdminDashboardPage.jsx'));
export const AdminUsers = lazyWithRetry(() => import('../pages/admin/AdminUsers.jsx'));
export const AdminLoads = lazyWithRetry(() => import('../pages/admin/AdminLoads.jsx'));
export const AdminBids = lazyWithRetry(() => import('../pages/admin/AdminBids.jsx'));
export const AdminNotifications = lazyWithRetry(() => import('../pages/admin/AdminNotifications.jsx'));
export const AdminOtpLogs = lazyWithRetry(() => import('../pages/admin/AdminOtpLogs.jsx'));
export const AdminRoleManagement = lazyWithRetry(() => import('../pages/admin/AdminRoleManagement.jsx'));
export const VerificationQueue = lazyWithRetry(() => import('../pages/admin/VerificationQueue.jsx'));
export const Disputes = lazyWithRetry(() => import('../pages/admin/Disputes.jsx'));
export const ShipmentControl = lazyWithRetry(() => import('../pages/admin/ShipmentControl.jsx'));
export const LoadsHub = lazyWithRetry(() => import('../pages/loads/LoadsHub.jsx'));
export const LoadDetails = lazyWithRetry(() => import('../pages/loads/LoadDetails.jsx'));
export const BidManagement = lazyWithRetry(() => import('../pages/bids/BidManagement.jsx'));
export const MyBids = lazyWithRetry(() => import('../pages/bids/MyBids.jsx'));
export const ShipmentTracking = lazyWithRetry(() => import('../pages/shipments/ShipmentTracking.jsx'));
export const Messages = lazyWithRetry(() => import('../pages/messages/Messages.jsx'));
export const TruckDetails = lazyWithRetry(() => import('../pages/carrier/TruckDetails.jsx'));
export const PublicProfile = lazyWithRetry(() => import('../pages/profile/PublicProfile.jsx'));
